# -*- coding: utf-8 -*-
"""Mad Libs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlDyALNF5nzfhLg4Y84ryV1saKjXZMG9
"""

print("Welcome TO Mad Libs!")
name = input("Enter a Name:")
adjective = input("Enter a Adjective:")
noun = input("Enter a Noun:")
place = input("Enter a Verb:")
object = input("Enter a Object:")
emotion = input("Enter a Emotion:")
animal = input("Enter a Plural Animal:")
random_object = input("Enter a random object:")
food = input("Enter a food:")



mad_libs_story = f"""
Once upon a time, there was a {adjective} adventurer named{name}. One day, {name} decided to travel to the {place} to find a hidden {noun}. With a {adjective} map in hand, they packed their {object} and set off on their journey.

As {name} walked through the {adjective} forest, they suddenly encountered a {animal} that was {adjective} and looked very {emotion}. {name} quickly grabbed their {random_object} and used it to {verb}, scaring the creature away.

After the {adjective} encounter, {name} finally reached the {noun} hidden in a {adjective} cave. To celebrate, they {verb} happily and ate a delicious {food} before heading back home.

And from that day on, {name} was known as the most {adjective} adventurer in all of {place}
"""


print("Here is your Mad Libs story!")
print(mad_libs_story)